# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.3.0"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/hako/durafmt"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lrstanley/girc"

[[constraint]]
  name = "github.com/ogier/pflag"
  version = "0.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "mvdan.cc/xurls"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
